imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        
        mappings:
            payum_paypal_express_checkout_nvp:
                is_bundle: false
                type: xml 
                dir: %kernel.root_dir%/../vendor/payum/paypal-express-checkout-nvp/src/Payum/Paypal/ExpressCheckout/Nvp/Bridge/Doctrine/Resources/mapping
                prefix: Payum\Paypal\ExpressCheckout\Nvp\Bridge\Doctrine\Entity

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }
    
payum:
    contexts:
        simple_purchase_paypal_express_checkout:
            paypal_express_checkout_nvp_payment:
                api:
                    options:
                        username:  %paypal.express_checkout.username%
                        password:  %paypal.express_checkout.password%
                        signature: %paypal.express_checkout.signature%
                        sandbox: true

            filesystem_storage:
                model_class: Acme\PaypalExpressCheckoutBundle\Model\PaymentDetails
                storage_dir: %kernel.root_dir%/Resources/payments
                id_property: id
                
        simple_purchase_paypal_express_checkout_doctrine:
            paypal_express_checkout_nvp_payment:
                api:
                    options:
                        username:  %paypal.express_checkout.username%
                        password:  %paypal.express_checkout.password%
                        signature: %paypal.express_checkout.signature%
                        sandbox: true

            doctrine_storage:
                driver: orm
                model_class: Acme\PaypalExpressCheckoutBundle\Entity\PaymentDetails
                
        simple_recurring_payment_paypal_express_checkout:
            paypal_express_checkout_nvp_payment:
                api:
                    options:
                        username:  %paypal.express_checkout.username%
                        password:  %paypal.express_checkout.password%
                        signature: %paypal.express_checkout.signature%
                        sandbox: true

            filesystem_storage:
                model_class: Acme\PaypalExpressCheckoutBundle\Model\PaymentDetails
                storage_dir: %kernel.root_dir%/Resources/payments
                id_property: id

        simple_purchase_paypal_pro:
            paypal_pro_checkout_nvp_payment:
                api:
                    options: %paypal.pro_checkout%
                
        simple_purchase_authorize_net:
            authorize_net_aim_payment:
                api:
                    options:
                        login_id: %authorize_net.login_id%
                        transaction_key: %authorize_net.transaction_key%
                        sandbox: true

            filesystem_storage:
                model_class: Acme\PaymentBundle\Model\AuthorizeNetInstruction
                storage_dir: %kernel.root_dir%/Resources/payments
                id_property: id

        simple_purchase_be2bill:
            be2bill_payment:
                api:
                    options:
                        identifier: %be2bill.identifier%
                        password: %be2bill.password%
                        sandbox: true

            filesystem_storage:
                model_class: Acme\PaymentBundle\Model\Be2BillInstruction
                storage_dir: %kernel.root_dir%/Resources/payments
                id_property: id
                
        simple_purchase_paypal_express_via_ominpay:
            omnipay_payment:
                type: PayPal_Express
                options:
                    username:  %paypal.express_checkout.username%
                    password:  %paypal.express_checkout.password%
                    signature: %paypal.express_checkout.signature%
                    testMode: true
                    
            filesystem_storage:
                model_class: Acme\PaymentBundle\Model\OmnipayInstruction
                storage_dir: %kernel.root_dir%/Resources/payments
                id_property: id
