payum:
    storages:
        Acme\PaymentBundle\Entity\PaymentDetails:
            extension:
                all: true
            doctrine: orm

        Acme\PaymentBundle\Document\PaymentDetails:
            extension:
                gateways:
                    - paypal_express_checkout_and_doctrine_mongo_odm
            doctrine: mongodb

        Acme\PaymentBundle\Entity\AgreementDetails:
            extension:
                gateways:
                    - paypal_express_checkout_recurring_payment_and_doctrine_orm
            doctrine: orm

        Acme\PaymentBundle\Entity\RecurringPaymentDetails:
            extension:
                gateways:
                    - paypal_express_checkout_recurring_payment_and_doctrine_orm
            doctrine: orm

        Acme\PaymentBundle\Model\AgreementDetails:
            extension:
                gateways:
                    - payex_agreement
            filesystem:
                storage_dir: %kernel.root_dir%/Resources/payments
                id_property: id

        Acme\OtherExamplesBundle\Model\Cart:
            extension:
                gateways:
                    - paypal_express_checkout_plus_cart
                    - authorize_net_plus_cart
            filesystem:
                storage_dir: %kernel.root_dir%/Resources/payments
                id_property: id

        JMS\Payment\CoreBundle\Entity\Payment:
            extension:
                gateways:
                    - paypal_express_checkout_via_jms_plugin
            doctrine: orm

        Acme\PaymentBundle\Model\PaymentDetails:
            filesystem:
                storage_dir: %kernel.root_dir%/Resources/payments
                id_property: id

        Payum\Core\Model\Payment:
            filesystem:
                storage_dir: %kernel.root_dir%/Resources/payments
                id_property: number

    security:
        token_storage:
            Acme\PaymentBundle\Entity\PaymentSecurityToken: { doctrine: orm }

    dynamic_gateways:
        sonata_admin: true
        config_storage:
            Acme\PaymentBundle\Entity\GatewayConfig: { doctrine: orm }

    gateways:
        paypal_express_checkout_and_doctrine_orm:
            paypal_express_checkout_nvp:
                username:  %paypal.express_checkout.username%
                password:  %paypal.express_checkout.password%
                signature: %paypal.express_checkout.signature%
                sandbox: true

        paypal_express_checkout_and_doctrine_mongo_odm:
            paypal_express_checkout_nvp:
                username:  %paypal.express_checkout.username%
                password:  %paypal.express_checkout.password%
                signature: %paypal.express_checkout.signature%
                sandbox: true

        paypal_express_checkout_recurring_payment_and_doctrine_orm:
            paypal_express_checkout_nvp:
                username:  %paypal.express_checkout.username%
                password:  %paypal.express_checkout.password%
                signature: %paypal.express_checkout.signature%
                sandbox: true

        paypal_express_checkout_with_ipn_enabled:
            paypal_express_checkout_nvp:
                username:  %paypal.express_checkout.username%
                password:  %paypal.express_checkout.password%
                signature: %paypal.express_checkout.signature%
                sandbox: true
                actions:
                    - acme.payment.payum.action.store_notification

        paypal_express_checkout_and_custom_api:
            paypal_express_checkout_nvp:
                username:  NOT NEEDED
                password:  NOT NEEDED
                signature: NOT NEEDED
                sandbox: true
                apis:
                    - acme.payment.payum.paypal_express_checkout_api

        paypal_pro_checkout:
            paypal_pro_checkout_nvp:
                username: %paypal.pro_checkout.username%
                password: %paypal.pro_checkout.password%
                partner:  %paypal.pro_checkout.partner%
                vendor:   %paypal.pro_checkout.vendor%
                sandbox: true

        authorize_net:
            authorize_net_aim:
                login_id: %authorize_net.login_id%
                transaction_key: %authorize_net.transaction_key%
                sandbox: true

        be2bill:
            be2bill_direct:
                identifier: %be2bill.identifier%
                password: %be2bill.password%
                sandbox: true

        be2bill_offsite:
            be2bill_offsite:
                identifier: %be2bill.identifier%
                password: %be2bill.password%
                sandbox: true
                actions:
                    - acme.payex.payum.action.store_notification

        klarna_invoice:
            klarna_invoice:
                secret: %klarna.invoice.secret%
                eid: %klarna.invoice.eid%
                sandbox: true

        klarna_checkout:
            klarna_checkout:
                secret: %klarna.checkout.secret%
                merchant_id: %klarna.checkout.eid%
                sandbox: true
                extensions:
                    - acme.payment.payum.extension.store_notification

        paypal_express_checkout_via_omnipay:
            omnipay_offsite:
                type: PayPal_Express
                options:
                    username:  %paypal.express_checkout.username%
                    password:  %paypal.express_checkout.password%
                    signature: %paypal.express_checkout.signature%
                    testMode: true

        stripe_js:
            stripe_js:
                publishable_key: %stripe.publishable_key%
                secret_key: %stripe.secret_key%

        stripe_checkout:
            stripe_checkout:
                publishable_key: %stripe.publishable_key%
                secret_key: %stripe.secret_key%

        stripe_via_omnipay:
            omnipay_direct:
                type: Stripe
                options:
                    apiKey:  %stripe.secret_key%
                    testMode: true

        payex:
            payex:
                account_number:  %payex.account_number%
                encryption_key:  %payex.encryption_key%
                sandbox: true
                actions:
                    - acme.payex.payum.action.store_notification

        payex_agreement:
            payex:
                account_number:  %payex.account_number%
                encryption_key:  %payex.encryption_key%
                sandbox: true

        redsys:
            redsys:
                merchant_code:  %redsys.merchant_code%
                terminal:  %redsys.terminal%
                secret_key: %redsys.secret_key%
                sandbox: true

        trustly:
            trustly:
                rsa_private_key:  %trustly.rsa_private_key%
                username:  %trustly.username%
                password: %trustly.password%
                sandbox: true

        paypal_express_checkout_plus_cart:
            paypal_express_checkout_nvp:
                username:  %paypal.express_checkout.username%
                password:  %paypal.express_checkout.password%
                signature: %paypal.express_checkout.signature%
                sandbox: true
                actions:
                    - other_examples.payum.action.capture_cart_with_paypal_express_checkout
                    - other_examples.payum.action.status_details_aggregated_null_model

        authorize_net_plus_cart:
            authorize_net_aim:
                login_id: %authorize_net.login_id%
                transaction_key: %authorize_net.transaction_key%
                sandbox: true
                actions:
                    - other_examples.payum.action.capture_cart_with_authorize_net
                    - other_examples.payum.action.status_details_aggregated_null_model

        paypal_express_checkout_via_jms_plugin:
            jms_payment_plugin: ~

        offline:
            offline: ~

        foo_bar_gateway:
            foo_bar_gateway:
                username: aName
                password: aPass