payum:
    security:
        token_storage:
            Acme\PaymentBundle\Entity\PaymentSecurityToken:
                doctrine:
                    driver: orm

    contexts:
        paypal_express_checkout_and_doctrine_orm:
            paypal_express_checkout_nvp:
                api:
                    options:
                        username:  %paypal.express_checkout.username%
                        password:  %paypal.express_checkout.password%
                        signature: %paypal.express_checkout.signature%
                        sandbox: true

            storages:
                Acme\PaymentBundle\Entity\PaymentDetails:
                    doctrine:
                        driver: orm

        paypal_express_checkout_and_doctrine_mongo_odm:
            paypal_express_checkout_nvp:
                api:
                    options:
                        username:  %paypal.express_checkout.username%
                        password:  %paypal.express_checkout.password%
                        signature: %paypal.express_checkout.signature%
                        sandbox: true

            storages:
                Acme\PaymentBundle\Document\PaymentDetails:
                    doctrine:
                        driver: mongodb

        paypal_express_checkout_recurring_payment_and_doctrine_orm:
            paypal_express_checkout_nvp:
                api:
                    options:
                        username:  %paypal.express_checkout.username%
                        password:  %paypal.express_checkout.password%
                        signature: %paypal.express_checkout.signature%
                        sandbox: true

            storages:
                Acme\PaymentBundle\Entity\AgreementDetails:
                    doctrine:
                        driver: orm

                Acme\PaymentBundle\Entity\RecurringPaymentDetails:
                    doctrine:
                        driver: orm

        paypal_express_checkout_with_ipn_enabled:
            paypal_express_checkout_nvp:
                api:
                    options:
                        username:  %paypal.express_checkout.username%
                        password:  %paypal.express_checkout.password%
                        signature: %paypal.express_checkout.signature%
                        sandbox: true
                actions:
                    - acme.payment.payum.action.store_notification

            storages:
                Acme\PaymentBundle\Entity\PaymentDetails:
                    doctrine:
                        driver: orm

        paypal_express_checkout_and_custom_api:
            paypal_express_checkout_nvp:
                api:
                    options:
                        username:  NOT NEEDED
                        password:  NOT NEEDED
                        signature: NOT NEEDED
                        sandbox: true
                apis:
                    - acme.payment.payum.paypal_express_checkout_api

            storages:
                Acme\PaymentBundle\Entity\PaymentDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: id
                        payment_extension: true

        paypal_pro_checkout:
            paypal_pro_checkout_nvp:
                api:
                    options:
                        username: %paypal.pro_checkout.username%
                        password: %paypal.pro_checkout.password%
                        partner:  %paypal.pro_checkout.partner%
                        vendor:   %paypal.pro_checkout.vendor%
                        sandbox: true
            storages:
                Acme\PaymentBundle\Model\PaymentDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: id

        authorize_net:
            authorize_net_aim:
                api:
                    options:
                        login_id: %authorize_net.login_id%
                        transaction_key: %authorize_net.transaction_key%
                        sandbox: true
            storages:
                Acme\PaymentBundle\Model\PaymentDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: id

        be2bill:
            be2bill:
                api:
                    options:
                        identifier: %be2bill.identifier%
                        password: %be2bill.password%
                        sandbox: true

            storages:
                Acme\PaymentBundle\Model\PaymentDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: id

        be2bill_onsite:
            be2bill:
                api:
                    options:
                        identifier: %be2bill.identifier%
                        password: %be2bill.password%
                        sandbox: true
                actions:
                    - acme.payex.payum.action.store_notification

            storages:
                Acme\PaymentBundle\Model\PaymentDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: id

        klarna_checkout:
            klarna_checkout:
                api:
                    options:
                        secret: %klarna.checkout.secret%
                        sandbox: true

            storages:
                Acme\PaymentBundle\Model\PaymentDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: id

        paypal_express_checkout_via_ominpay:
            omnipay:
                type: PayPal_Express
                options:
                    username:  %paypal.express_checkout.username%
                    password:  %paypal.express_checkout.password%
                    signature: %paypal.express_checkout.signature%
                    testMode: true

            storages:
                Acme\PaymentBundle\Model\PaymentDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: id

        stripe_via_omnipay:
            omnipay:
                type: Stripe
                options:
                    apiKey:  %stripe.secret_key%
                    testMode: true

            storages:
                Acme\PaymentBundle\Model\PaymentDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: id

        payex:
            payex:
                api:
                    options:
                        account_number:  %payex.account_number%
                        encryption_key:  %payex.encryption_key%
                        sandbox: true
                actions:
                    - acme.payex.payum.action.store_notification
            storages:
                Acme\PaymentBundle\Model\PaymentDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: id

        payex_agreement:
            payex:
                api:
                    options:
                        account_number:  %payex.account_number%
                        encryption_key:  %payex.encryption_key%
                        sandbox: true
            storages:
                Acme\PaymentBundle\Model\PaymentDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: id

                Acme\PaymentBundle\Model\AgreementDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: agreementRef

        paypal_express_checkout_plus_cart:
            paypal_express_checkout_nvp:
                api:
                    options:
                        username:  %paypal.express_checkout.username%
                        password:  %paypal.express_checkout.password%
                        signature: %paypal.express_checkout.signature%
                        sandbox: true
                actions:
                    - other_examples.payum.action.capture_cart_with_paypal_express_checkout
                    - other_examples.payum.action.status_details_aggregated_null_model

            storages:
                Acme\OtherExamplesBundle\Model\Cart:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: id

                Acme\PaymentBundle\Model\PaymentDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: id

        authorize_net_plus_cart:
            authorize_net_aim:
                api:
                    options:
                        login_id: %authorize_net.login_id%
                        transaction_key: %authorize_net.transaction_key%
                        sandbox: true
                actions:
                    - other_examples.payum.action.capture_cart_with_authorize_net
                    - other_examples.payum.action.status_details_aggregated_null_model

            storages:
                Acme\OtherExamplesBundle\Model\Cart:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: id
                Acme\PaymentBundle\Model\PaymentDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: id

        paypal_express_checkout_via_jms_plugin:
            jms_payment_plugin: ~
            storages:
                JMS\Payment\CoreBundle\Entity\Payment:
                    doctrine:
                        driver: orm

        offline:
            offline: ~

            storages:
                Acme\PaymentBundle\Model\PaymentDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: id

        foo_bar_gateway:
            foo_bar_gateway:
                username: aName
                password: aPass

            storages:
                Acme\PaymentBundle\Model\PaymentDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: id