_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo

_welcome:
    pattern:  /
    defaults: { _controller: AcmePaymentBundle:Default:index }
    
payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"
    prefix:   /

payum_authorize:
    resource: "@PayumBundle/Resources/config/routing/authorize.xml"
    prefix:   /
    
payum_sync:
    resource: "@PayumBundle/Resources/config/routing/sync.xml"
    prefix:   /
    
payum_notify:
    resource: "@PayumBundle/Resources/config/routing/notify.xml"
    prefix:   /

payum_refund:
    resource: "@PayumBundle/Resources/config/routing/refund.xml"
    prefix:   /

acme_paypal_express_checkout:
    resource: "@AcmePaypalExpressCheckoutBundle/Resources/config/routing.yml"
    prefix:   /

acme_stripe:
    resource: "@AcmeStripeBundle/Resources/config/routing.yml"
    prefix:   /
    
acme_payex:
    resource: "@AcmePayexBundle/Resources/config/routing.yml"
    prefix:   /

acme_klarna:
    resource: "@AcmeKlarnaBundle/Resources/config/routing.yml"
    prefix:   /

acme_other_examples:
    resource: "@AcmeOtherExamplesBundle/Resources/config/routing.yml"
    prefix:   /

acme_payment:
    resource: "@AcmePaymentBundle/Resources/config/routing.yml"
    prefix:   /
