_welcome:
    pattern:  /
    defaults: { _controller: AcmePaymentBundle:Demo:list }

acme_paypal_express_checkout:
    resource: "@AcmePaypalExpressCheckoutBundle/Resources/config/routing.yml"
    prefix:   /

acme_payment:
    resource: "@AcmePaymentBundle/Resources/config/routing.yml"
    prefix:   /
